// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9h9vcn3xB8iFFQalPaYnYZP8RURyEb54',
    appId: '1:246271214828:web:33dd6e5426d0ffab2f51c9',
    messagingSenderId: '246271214828',
    projectId: 'expense-tracker-da0fc',
    authDomain: 'expense-tracker-da0fc.firebaseapp.com',
    storageBucket: 'expense-tracker-da0fc.firebasestorage.app',
    measurementId: 'G-YDHHSNFBW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSEm4VwjD9OOCflMd1-duFIoc2-KUoZ-U',
    appId: '1:246271214828:android:40882b56eab753652f51c9',
    messagingSenderId: '246271214828',
    projectId: 'expense-tracker-da0fc',
    storageBucket: 'expense-tracker-da0fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeQRo1Zj2f_YJqLAD8pljalvdzzUzFoPQ',
    appId: '1:246271214828:ios:0589a783ca8769012f51c9',
    messagingSenderId: '246271214828',
    projectId: 'expense-tracker-da0fc',
    storageBucket: 'expense-tracker-da0fc.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeQRo1Zj2f_YJqLAD8pljalvdzzUzFoPQ',
    appId: '1:246271214828:ios:0589a783ca8769012f51c9',
    messagingSenderId: '246271214828',
    projectId: 'expense-tracker-da0fc',
    storageBucket: 'expense-tracker-da0fc.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9h9vcn3xB8iFFQalPaYnYZP8RURyEb54',
    appId: '1:246271214828:web:f3f79da4a49c7a062f51c9',
    messagingSenderId: '246271214828',
    projectId: 'expense-tracker-da0fc',
    authDomain: 'expense-tracker-da0fc.firebaseapp.com',
    storageBucket: 'expense-tracker-da0fc.firebasestorage.app',
    measurementId: 'G-JSLRKT4LJ9',
  );
}
